defaults:
  - _self_
  - data: cifar10
  - model: cnn2
  - override hydra/help: help

alpha: 0.01
w: 0.1

gamma: 0.1

fv_domain: freq
fv_dist: uniform
fv_sd: 1e-1 

n_epochs: 2
lr: 1e-6
batch_size: 16
sample_batch_size: 16

model_dir:  ./assets/ 
data_dir:  ./assets/ 
output_dir:  ./model_weights/
target_img_path: ./assets/adv_train/fake.jpg

train_original: true
img_str:  cross 
replace_relu: true
device: "cuda:0"
